name: IrRubyConf 2015
markdown: redcarpet
highlighter: pygments
url: http://2015.iranonrails.ir
description: Iran Ruby Conference 2015
copyright: copyright 2014-2015 @iranonrails
rss_path: /feed
rss_name: feed.xml
rss_post_limit: 10
tag_page_layout: tag_page
tag_page_dir: tag
lsi: false
paginate: 10
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile']
source: ./src
destination: ./build
permalink: /blog/posts/:categories/:title/
paginate_path: "blog/page:num"

assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: true
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
